import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FlexLayoutModule } from '@angular/flex-layout';
import {
  MatToolbarModule,
  MatIconModule,
  MatButtonModule,
  MatCardModule,
  MatTooltipModule,
  MatSnackBarModule,
  MatAutocompleteModule,
  MatFormFieldModule,
  MatInputModule,
  MatPaginatorModule,
  MatDialogModule,
  MatCheckboxModule,
  MatListModule,
  MatRadioModule,
  MatGridListModule,
  MatStepperModule,
  MatMenuModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSliderModule,
  MatTreeModule,
  MatSidenavModule,
  MatBadgeModule,
  MatExpansionModule,
  MatSelectModule,
  MatChipsModule,
  MatTableModule,
  MatDividerModule,
  MatSortModule,
  MatButtonToggleModule,
  MatRippleModule,
  MatTabsModule,
  MatDatepickerModule,
  MatNativeDateModule 
} from '@angular/material';
import { BookingDialogComponent } from './booking-dialog/booking-dialog.component';
@NgModule({
  declarations: [BookingDialogComponent],
  imports: [
    CommonModule,
    FormsModule,
    FlexLayoutModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatRadioModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatStepperModule,
    MatMenuModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatTreeModule,
    MatToolbarModule,
    MatSidenavModule,
    MatBadgeModule,
    MatExpansionModule,
    MatSelectModule,
    MatCheckboxModule,
    MatChipsModule,
    MatTableModule,
    MatDividerModule,
    MatSortModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatRippleModule,
    MatTabsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    ReactiveFormsModule,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    FlexLayoutModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatRadioModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatStepperModule,
    MatMenuModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatSliderModule,
    MatSnackBarModule,
    MatTooltipModule,
    MatTreeModule,
    MatToolbarModule,
    MatSidenavModule,
    MatBadgeModule,
    MatExpansionModule,
    MatSelectModule,
    MatCheckboxModule,
    MatChipsModule,
    MatTableModule,
    MatDividerModule,
    MatSortModule,
    MatButtonToggleModule,
    MatPaginatorModule,
    MatRippleModule,
    MatTabsModule,
    MatDatepickerModule,
    MatNativeDateModule,
    BookingDialogComponent
  ],
  entryComponents: [BookingDialogComponent]
})
export class SharedModule { }
